// 0508/0508-1215/src/components/ImageUploader.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Upload, ImageIcon } from 'lucide-vue-next'

const emit = defineEmits<{
  (e: 'upload', files: FileList): void
}>()

const isDragging = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

function handleDragOver(e: DragEvent) {
  e.preventDefault()
  isDragging.value = true
}

function handleDragLeave() {
  isDragging.value = false
}

function handleDrop(e: DragEvent) {
  e.preventDefault()
  isDragging.value = false
  const files = e.dataTransfer?.files
  if (files && files.length > 0) {
    emit('upload', files)
  }
}

function handleClick() {
  fileInput.value?.click()
}

function handleFileSelect(e: Event) {
  const target = e.target as HTMLInputElement
  const files = target.files
  if (files && files.length > 0) {
    emit('upload', files)
    target.value = ''
  }
}
</script>

<template>
  <div
    class="border-2 border-dashed rounded-xl p-8 text-center transition-all duration-300 cursor-pointer"
    :class="[
      isDragging 
        ? 'border-primary-500 bg-primary-50' 
        : 'border-gray-300 hover:border-primary-400 hover:bg-gray-50'
    ]"
    @dragover="handleDragOver"
    @dragleave="handleDragLeave"
    @drop="handleDrop"
    @click="handleClick"
  >
    <input
      ref="fileInput"
      type="file"
      multiple
      accept="image/png,image/jpeg,image/webp"
      class="hidden"
      @change="handleFileSelect"
    />
    <div class="flex flex-col items-center gap-4">
      <div 
        class="w-16 h-16 rounded-full flex items-center justify-center transition-colors"
        :class="isDragging ? 'bg-primary-500' : 'bg-primary-100'"
      >
        <Upload 
          class="w-8 h-8" 
          :class="isDragging ? 'text-white' : 'text-primary-600'"
        />
      </div>
      <div>
        <p class="text-lg font-medium text-gray-700">拖拽图片到这里</p>
        <p class="text-sm text-gray-500 mt-1">或点击选择文件</p>
      </div>
      <div class="flex items-center gap-2 text-xs text-gray-400">
        <ImageIcon class="w-4 h-4" />
        <span>支持 PNG、JPG、WebP 格式</span>
      </div>
    </div>
  </div>
</template>

// 0508/0508-414/src/components/ImageUploader.tsx
import React, { useRef, useState, useCallback } from 'react';
import { Upload, Image as ImageIcon, X } from 'lucide-react';

interface ImageUploaderProps {
  onImageLoaded: (imageData: ImageData, width: number, height: number) => void;
  previewUrl?: string;
}

export default function ImageUploader({ onImageLoaded, previewUrl }: ImageUploaderProps) {
  const [isDragging, setIsDragging] = useState(false);
  const [preview, setPreview] = useState<string | null>(previewUrl || null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const handleFile = useCallback((file: File) => {
    if (!file.type.match('image/png') && !file.type.match('image/bmp')) {
      alert('请上传 PNG 或 BMP 格式的图片');
      return;
    }

    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new Image();
      img.onload = () => {
        if (canvasRef.current) {
          const canvas = canvasRef.current;
          canvas.width = img.width;
          canvas.height = img.height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            ctx.drawImage(img, 0, 0);
            const imageData = ctx.getImageData(0, 0, img.width, img.height);
            onImageLoaded(imageData, img.width, img.height);
          }
        }
        setPreview(e.target?.result as string);
      };
      img.src = e.target?.result as string;
    };
    reader.readAsDataURL(file);
  }, [onImageLoaded]);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
    
    const file = e.dataTransfer.files[0];
    if (file) {
      handleFile(file);
    }
  }, [handleFile]);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleInputChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleFile(file);
    }
  }, [handleFile]);

  const handleClear = useCallback(() => {
    setPreview(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
    onImageLoaded(new ImageData(1, 1), 0, 0);
  }, [onImageLoaded]);

  return (
    <div className="w-full">
      <canvas ref={canvasRef} className="hidden" />
      <input
        ref={fileInputRef}
        type="file"
        accept=".png,.bmp"
        onChange={handleInputChange}
        className="hidden"
      />
      
      {!preview ? (
        <div
          onDrop={handleDrop}
          onDragOver={handleDragOver}
          onDragLeave={handleDragLeave}
          onClick={() => fileInputRef.current?.click()}
          className={`upload-zone rounded-2xl p-12 text-center cursor-pointer transition-all duration-300 ${
            isDragging ? 'dragover' : ''
          }`}
        >
          <div className="flex flex-col items-center gap-4">
            <div className="w-16 h-16 rounded-full bg-accent-500/10 flex items-center justify-center">
              <Upload className="w-8 h-8 text-accent-400" />
            </div>
            <div>
              <p className="text-lg font-medium text-slate-200">拖拽图片到此处</p>
              <p className="text-sm text-slate-400 mt-1">或点击选择文件</p>
            </div>
            <p className="text-xs text-slate-500">支持 PNG、BMP 格式</p>
          </div>
        </div>
      ) : (
        <div className="relative group">
          <div className="rounded-2xl overflow-hidden border border-accent-500/30">
            <img
              src={preview}
              alt="Preview"
              className="w-full max-h-80 object-contain bg-slate-900/50"
            />
          </div>
          <button
            onClick={handleClear}
            className="absolute top-3 right-3 w-8 h-8 rounded-full bg-red-500/90 hover:bg-red-500 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-200"
          >
            <X className="w-4 h-4 text-white" />
          </button>
        </div>
      )}
    </div>
  );
}
