// 0508/0508-1300/src/components/PresetSelector.vue
<script setup lang="ts">
import { inject } from 'vue'
import { usePresets } from '@/composables/usePresets'
import { Sparkles } from 'lucide-vue-next'
import type { useLissajous } from '@/composables/useLissajous'

type LissajousInstance = ReturnType<typeof useLissajous>

const lissajous = inject<LissajousInstance>('lissajous')

const { getAllPresets, currentPresetId, applyPreset: applyPresetToStore } = usePresets()
const { applyPreset: applyPresetToLissajous } = lissajous!

const presets = getAllPresets()

function handlePresetClick(presetId: string) {
  applyPresetToStore(presetId, applyPresetToLissajous)
}
</script>

<template>
  <div class="preset-selector">
    <div class="flex items-center gap-2 mb-4">
      <Sparkles class="w-5 h-5 text-amber-400" />
      <h2 class="text-lg font-semibold text-gray-800 dark:text-gray-100">预置图形</h2>
    </div>

    <div class="grid grid-cols-2 gap-3">
      <button
        v-for="preset in presets"
        :key="preset.id"
        @click="handlePresetClick(preset.id)"
        class="preset-card group"
        :class="{ 'preset-card-active': currentPresetId === preset.id }"
      >
        <div class="text-3xl mb-2">{{ preset.icon }}</div>
        <div class="text-sm font-medium text-gray-800 dark:text-gray-100">{{ preset.name }}</div>
        <div class="text-xs text-gray-500 dark:text-gray-400 mt-1">{{ preset.description }}</div>
      </button>
    </div>
  </div>
</template>

<style scoped>
.preset-card {
  @apply flex flex-col items-center justify-center p-4 rounded-xl bg-white dark:bg-gray-800;
  @apply border-2 border-gray-200 dark:border-gray-700;
  @apply transition-all duration-300 ease-out cursor-pointer;
  @apply hover:scale-105 hover:border-indigo-400 dark:hover:border-indigo-500;
  @apply hover:shadow-lg hover:shadow-indigo-500/20;
}

.preset-card-active {
  @apply border-indigo-500 dark:border-indigo-400;
  @apply shadow-lg shadow-indigo-500/40;
  animation: glow 2s ease-in-out infinite;
}

@keyframes glow {
  0%, 100% {
    box-shadow: 0 0 10px rgba(99, 102, 241, 0.4), 0 0 20px rgba(99, 102, 241, 0.2);
  }
  50% {
    box-shadow: 0 0 20px rgba(99, 102, 241, 0.6), 0 0 40px rgba(99, 102, 241, 0.3);
  }
}
</style>

// 0508/0508-427/src/components/PresetSelector.tsx
import { useCircuitStore, PRESETS } from '@/store/circuitStore';

export default function PresetSelector() {
  const { activePreset, setActivePreset } = useCircuitStore();

  return (
    <div className="animate-fade-in-up" style={{ animationDelay: '200ms' }}>
      <div className="glass-card p-5 glass-card-hover transition-all duration-300">
        <h2 className="text-sm font-bold uppercase tracking-widest text-cyan-400 mb-4 flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-cyan-400 animate-glow-pulse" />
          预设场景
        </h2>
        <div className="flex flex-wrap gap-2">
          {PRESETS.map((preset) => {
            const isActive = activePreset === preset.id;
            return (
              <button
                key={preset.id}
                onClick={() => setActivePreset(preset.id)}
                className={`
                  group relative px-4 py-2.5 rounded-lg text-xs font-medium
                  transition-all duration-300 cursor-pointer
                  ${
                    isActive
                      ? 'bg-cyan-400/15 border border-cyan-400/40 text-cyan-400 glow-cyan'
                      : 'bg-navy-700/50 border border-navy-500/50 text-slate-400 hover:border-cyan-400/20 hover:text-slate-300'
                  }
                `}
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm">{preset.icon}</span>
                  <div className="text-left">
                    <div className="font-bold">{preset.name}</div>
                    <div className={`text-[9px] ${isActive ? 'text-cyan-400/60' : 'text-slate-500'}`}>
                      {preset.description}
                    </div>
                  </div>
                </div>
                {isActive && (
                  <div className="absolute -top-px -right-px w-2 h-2 rounded-bl bg-cyan-400" />
                )}
              </button>
            );
          })}
        </div>
      </div>
    </div>
  );
}
